name: Release
on:
  workflow_dispatch:
  push:
    branches: [ master, alpha, beta ]

env:
  E_GITHUB_TOKEN: "${{ secrets.EXTOLE_GITHUB_PAT }}"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Release to production
        env:
          GITHUB_TOKEN: ${{ env.E_GITHUB_TOKEN }}
        run: npx semantic-release
